image: node:latest

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@13.0.3
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages